### ISSUE TITLE
Minor bug fix

### ISSUE THREAD

**Issue by Kai-46** [bmild/nerf#10]
I believe in **run_nerf.py**,  [line 532-533](https://github.com/bmild/nerf/blob/1649cbe413cc0e2883ad0d019c38668b549562dc/run_nerf.py#L532) needs to be moved forward, e.g., before [line 504](https://github.com/bmild/nerf/blob/1649cbe413cc0e2883ad0d019c38668b549562dc/run_nerf.py#L504), because the variable **global_step** is referenced in [line 513](https://github.com/bmild/nerf/blob/1649cbe413cc0e2883ad0d019c38668b549562dc/run_nerf.py#L513).

**Comment by bmild** [comment]
Thanks, modified the line 513 reference to use `start` instead of `global_step`
