### ISSUE TITLE
Creating a synthetic dataset with Unity: insufficient camera position precision

### ISSUE THREAD

**Issue by AndreaMas** [bmild/nerf#119]
Hi, I'm trying to create a synthetic dataset of a scene within Unity3D. I acquire images of a human model, spawning cameras in a semicircle (or in a halo, sometimes works best).

![Untitled](https://user-images.githubusercontent.com/32450751/131395295-0aec4195-abf3-454e-9633-5870771e7031.png)

I'm able to create an almost identical dataset to the ones blender generates (with test/train/val folders and relative transform_test/train/val.json files). However, since Unity does not support double-precision float to store camera position, the camera_to_world matrix has single-precision floats. As a result, I give NeRF less accurate camera positions.

I was hoping this would not be a problem, yet when running NeRF I get weird results. The output appears "gostly" and the overall result is blurred (besides, this is a lucky case, often it's just all white).

![Untitled 2](https://user-images.githubusercontent.com/32450751/131395447-2bf247ff-1ddc-458f-ac36-89d7a22aac43.png)

On the other hand, running NeRF using COLMAP to estimate the camera positions (using similar input images) gives really nice results.

So my question is: _**is it the poor precision in the camera position what is causing trouble? If the precision is enouth, what - in your experience - might be the problem?**_

Further details:

- Showed results obtained after 150000 iter. Settings are: no_batching=True, use_viewdirs=True, white_bkgd=True, N_samples=64, N_importance=64, N_rand=1024. Both input and output are 400x400px.

- The following shows the difference between my json vs how it should be. Do notice that my json stores camera position with less precision. My camera-to-world matrix has single-precision floats instead of double-precision ones:
![Untitled 1](https://user-images.githubusercontent.com/32450751/131395423-813336c0-3c3c-4f3f-a92f-84f19fd7258d.png)

- the model in the output video is positioned wrong. I suppose this is due to the difference in the coordinate systems between blender and unity. For sure this is fixable, just has to be noted to give a full picture.
https://user-images.githubusercontent.com/32450751/131395512-da3fa01b-2e65-44a4-87ea-fe99d2a6448e.mp4

- I don't know what the "rotation" parameter in the json file stands for, hoping it didn't matter I just set it to a random number (always 0.0125663). It doesn't seem to be used by the load_blender.py anyway.

PS: Thanks to the authors for sharing their work and code with everyone.

**Comment by AndreaMas** [comment]
Answer to myself: _**no, the problem it's not the inferior precision in camera position**_. With single-precision floats results should still look acceptable. 

I've verified this with the lego dataset in this repository. Modifying the json file, replacing double-precision with single-precision transform_matrix, results still look good.

I guess my problem might be the difference in coordinate systems between Blender and Unity.

**Comment by AndreaMas** [comment]
The issue for the "ghostly" effect was given by the absence of transparency in the training images. Images for blender datasets must have a transparent background, not white.

Also, the Unity's camera-to-world matrix must have its 2nd and 3rd row swapped, given that blender has the y axis pointing upwards, unlike Unity where its the z axis that points up.

**Comment by AndreaMas** [comment]
Hi @raynehe, no bother at all. Can you further describe the issue you're having?

I'll describe further the issue I had. I generated my own synthetic dataset in Unity, which had RGB images and camera positions and orientations with it. I realized that I was getting NeRF renders witch where very white. I solved the problem by fixing my dataset camera orientations and by giving a transparent background to my subject.

**Comment by AndreaMas** [comment]
Also, NeRF supports alpha channel, so it's not mandatory to transform RGBA images into RGB ones, although I'm not 100% sure this is the case for non-synthetic datasets

**Comment by raynehe** [comment]
Also, I set the intrinsic matrix using:
```python
focal = .5 * W / np.tan(0.5 * self.meta['camera_angle_x'])
intrinsics = np.array([[focal， 0，0.5*w],
                       [focal,0,0.5*H],
                       [0,0,1]]).tolist()

```

**Comment by AndreaMas** [comment]
This is what I found out on the transforms.json so far.

The transforms.json file contains the intrinsics and extrinsics of the cameras in the scene, the most important ones are:

- camera_angle_x: field-of-view in the x dimension, in radiants.
- frames: list of the camera-to-world transform matrices for each image.

Cameras share the OpenGL convention:
- point towards the negative z axis
- the positive x axis on the right
- the positive y axis on top

The json files were originally generated by the NeRF authors within Blender, whose world axis convection is:
- z upwards
- x and y respect the right hand rule.

A transform_martix as such:

[1,0,0,0]
[0,1,0,0]
[0,0,1,0]
[0,0,0,1]

represents a camera placed in the origin, pointing down, with the positive x axis on the right and the positive y axis on top.

If you find yourself within a different 3D program with different axis convenction, you'll need to account for that when generating datasets, (probably by swapping the rows of the matrix, or making rows negative).

**Comment by AndreaMas** [comment]
It's also important to understand the difference between the camera-to-world-matrix and the projection-martix. I'm still struggling with this topic so please check on this.

**Perspective Projection matrix**

Also known as PPM or camera-projection-matrix, projects the points in the world space onto the camera image plane.

PPM = K * world-to-camera-matrix

Where:

K = column of camera instrinsics
world-to-camera-matrix = ...

**World to camera matrix**

brings the points in the world space into camera space. Basically, rototranslates the whole world so that the camera is now centered on the origin.

world-to-camera-matrix =

                         [ M b ]
                         [ 0 1 ]

where M is a 3x3 matrix and b is a 3x1 vector.

**Camera to world matrix**

the inverse of the above, brings points from the camera space into the world space. This matrix therefore inherently represents the position and orientation of the camera within the world space.

camera-to-world-matrix = 

                         [ inv(M)    -inv(M) * b ]
                         [   0             1     ]

= 

                         [ R t ]
                         [ 0 1 ]

where R represents the rotation of the camera, while t its traslation wrt the origin of the world space.

So in your case, you would need to invert the camera before copying it to the transforms.json file.
