### ISSUE TITLE
`pi` in positional embedding?

### ISSUE THREAD

**Issue by yenchenlin** [bmild/nerf#12]
Hello, thanks for the nice work!

In the paper, the positional embedding has the term `pi` inside each `sin` and `cos`:

<img width="494" alt="Screen Shot 2020-03-30 at 7 50 53 PM" src="https://user-images.githubusercontent.com/7057863/77909349-ca811a80-72bf-11ea-801c-211cc9fba59b.png">

May I know where's `pi` in positional embedding's code [here](https://github.com/bmild/nerf/blob/master/run_nerf_helpers.py#L44)?

**Comment by bmild** [comment]
In practice, I omit the `pi` in the code to account for the fact that the scene bounds are a bit loose -- some samples spill out of the range [-1,1] for the `x` and `y` coordinates in real scene NDC, and a lot of the synthetic scenes are bounded more by [-1.5,1.5] than [-1,1]. I want to be sure to avoid the case where the lowest frequency positional encoding function wraps within the actual bounds of the scene. 

Another slight difference is that the implementation of `gamma` actually includes `p` in the output as well.

**Comment by yenchenlin** [comment]
> `avoid the case where the lowest frequency positional encoding function wraps within the actual bounds of the scene`

Do you mean something like `sin(2^k * -1.5pi)` and `sin(2^k * 0.5pi)` when `p = -1.5` and `0.5` are both within `[-1.5, 1.5]` bound?

**Comment by bmild** [comment]
Right, we don't want the periodicity to touch the actual scene content. It's like if we took the scene to be in [-1,1] but then further scaled it down by 1/pi.

**Comment by yenchenlin** [comment]
@bmild Thank you for your answer, I will close the issue now!
