### ISSUE TITLE
Questions about "spherify_poses" function

### ISSUE THREAD

**Issue by yjhong89** [bmild/nerf#121]
Hi. I am YJHong and thanks for your great work!

Can you introduce the general process of "spherify_poses" in "load_llff.py" file, please?

I coudn't find any mentions about this function.

As far as I understand, like "recenter_poses" function, first reset poses with the average poses in a spherical manner.

But, especially, I couldn't understand how "min_line_dst" function is derived.

![image](https://user-images.githubusercontent.com/26890721/133562558-60ad1dd2-3bdb-469d-a09e-bf9f88412993.png)

Thanks in advance!

**Comment by hirotong** [comment]
Hi, YJ, 

That function is used to get the point that is closest to the set of rays.  You can find the reference [here](https://silo.tips/download/least-squares-intersection-of-lines).

**Comment by yjhong89** [comment]
@hirotong 
Thank you!
