### ISSUE TITLE
Is it possible to release the .blend files for the synthetic datasets?

### ISSUE THREAD

**Issue by MultiPath** [bmild/nerf#13]
Hi,

I noticed the provided dataset only contained rendered images.
Is it also possible to provide your pre-processed .blend files (for instance, lego) so that we can use the model to render more views with different lightings? 

Thank you very much!

**Comment by tancik** [comment]
In the [synthetic data folder](https://drive.google.com/drive/u/1/folders/1JDdLGDruGNXWnM1eqY1FNL9PlStjaKWi) there is a readme file with links to all of the .blend files. The lego model can be found [here](www.blendswap.com/blend/11490).

**Comment by MultiPath** [comment]
Thanks. My question is that in your README you mentioned you modified a bit on the blend file. Do you have some guidance on what process you did and how to render these views (100 train/val/test) in your provided data? Thank you very much again!

**Comment by tancik** [comment]
I am attaching the blender rendering script that we used. Hopefully this can be a starting point. We are unfortunately unable to provide the modified .blend files. For reference, they were modified in the following ways:
+ Removed background elements
+ Remove compositing nodes
+ Remove extra cameras
+ Remove lights from scene
+ Add HDR environment lighting
+ Place target object at the origin and rescale to be visible in the camera

[360_view.py.zip](https://github.com/bmild/nerf/files/4410324/360_view.py.zip) (zipped to allow github sharing)

**Comment by MultiPath** [comment]
ok thanks! I will look into your scripts.
