### ISSUE TITLE
Scene with known camera poses

### ISSUE THREAD

**Issue by mertkiray** [bmild/nerf#132]
Hello, thank you for this project :)

I got a problem while training on a scene.

When I extracted the camera poses from COLMAP this is the output

https://user-images.githubusercontent.com/19538303/142732551-c89f3ed4-06c9-4567-a4d4-d2d5e3272bd9.mp4

the result is not so crispy as the scene is a little bit hard to learn but 

But when I use the camera poses from the dataset I got a result like this

https://user-images.githubusercontent.com/19538303/142732596-d1f68062-72f8-46f1-9608-36568be8fee7.mp4

The difference between the two is really great. I changed the gt camera poses to the coordinate system of right, upwards, backwards.

What am I doing wrong?

Thanks.

**Comment by h5jam** [comment]
I have got stuck on the same problem. Even tho camera poses are used for training steps from custom dataset captured from real world, it looks similar with your second video. Have you solved it?
