### ISSUE TITLE
Texture files for blender

### ISSUE THREAD

**Issue by llien30** [bmild/nerf#140]
Hi, Thank you for sharing the original blender files.
But I can't find the texture file for ship and chair. (Other texture files( .exr format) are in the blender)

How can I get these files?:
- 1D_cloth.png for the chair
- And other texture images to render the ship

Thanks!

**Comment by tancik** [comment]
The textures to render the ship can be found [here](https://www.blendswap.com/blend/8167). Attached is 1D_cloth.png
![1D_Cloth](https://user-images.githubusercontent.com/3310961/155186082-ecfc2366-d371-4ffb-b77e-c00669a50ce2.png)

**Comment by llien30** [comment]
Thank you :)
