### ISSUE TITLE
Opencv extrinsic instead of colmap

### ISSUE THREAD

**Issue by Duncan1115** [bmild/nerf#141]
Hi, Thanks for your great work of nerf !
Actually, Using colmap to estimate camera extrinsic spends much time (the installation and runing reconstrusction code...). I tried to put a chessboard in my own llff data and then calibrate it by using Opencv. However, the camera parameters could not be correctly used in nerf.
I think may be Opencv and colmap have different coordinate systems which makes the camera extrinsic in Opencv can not be used in the code. If you know the answer about how to transform the extrinsic, please tell me.
THANK U very much !!

**Comment by Duncan1115** [comment]
Already figured it out....   The important thing is to tranform the coordinate system from Opencv to Opengl. As follows:
1. get the w2c_opencv from Opencv calibration.
2. set a correctionMatrix, and then correctionMatrix multiplied by w2c_opencv to get w2c_opengl.
3. inverse w2c_opengl to get c2w_opengl.
I refer to this solution from this web: https://stackoverflow.com/questions/16265714/camera-pose-estimation-opencv-pnp/20373984#20373984

**Comment by ynma-hanvo** [comment]
great work and thanks for sharing.  but how many cameras in your system.

**Comment by Duncan1115** [comment]
Hi @ynma-hanvo , I use only one camera and one chessboard.

**Comment by ynma-hanvo** [comment]
@Duncan1115    ok, i see.  it means you compute the postions of consective frames by opencv.  that 's great.
but did you get satisfied result ?
