### ISSUE TITLE
How to train NeRF with pose from GPS or other sensors, not from COLMAP?

### ISSUE THREAD

**Issue by zeyu-hello** [bmild/nerf#155]
Thanks for this great work!

I have successfully run this repo with public dataset, but now for some reason I want to get rid of COLMAP.
Suppose we have a sequence of images along with their poses in our real world. Maybe these pose are recorded by GPS/IMU or other localization sensors, then how to directly parse thses poses for NeRF training?
I have noticed COLMAP generated poses are in OpenGL coordinate system, but haven't figured out how generate COLMAP style poses for training.

refer: https://amytabb.com/tips/tutorials/2019/06/28/OpenCV-to-OpenGL-tutorial-essentials/

Thanks!

**Comment by hontiky** [comment]
Hello @zeyu-hello!
I have the same question. If you closed this issue you probably find the answer, could you share your approach?
