### ISSUE TITLE
Re-rendering

### ISSUE THREAD

**Issue by arielbenitah** [bmild/nerf#16]
Hi, Thanks for this impressive work and for sharing the code.
Do you think it's possible - using your framework - to re-render a scene - for example with different illumination?
If yes, how would you proceed to do it?
Thanks

**Comment by bmild** [comment]
Changing the illumination isn't in scope of what NeRF's current capabilities: it learns a function encoding the directional light emitted at each point given a static scene and lighting. You'd have to have the network predict BRDF/material parameters to be able to relight it, and train with a set of known varying lightings or solve for the lighting in the scene as well as the object.

**Comment by arielbenitah** [comment]
Hi, 
thanks a lot for the answer.
