### ISSUE TITLE
Running Nerf on Mac

### ISSUE THREAD

**Issue by Ikhadija-5** [bmild/nerf#168]
I am trying to run nerf on Mac but i get the following error when creating an environment

ResolvePackageNotFound: 
  - tensorflow-gpu==1.15
  - cudatoolkit=10.0

Can someone help me with this?

**Comment by cwchenwang** [comment]
Mac doesn't have GPUs so there is no tensorflow-gpu and cudatoolkit, maybe you could try tensorflow versions especially for mac

**Comment by Ikhadija-5** [comment]
Thank you for the feedback

**Comment by JulienRineau** [comment]
Hey, have you fixed this issue ? I'm having the same problem.
Does it works if we simply install tensorflow==1.15 ?
