### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by crmabs** [bmild/nerf#17]
Is there a write up somewhere how to install the environment needed to run the demos?
 Currently my main problem is not to be able to downgrade the Cuda toolkit from 10.2 to 10.1 as tensorflow 1.15 requires it.

**Comment by bmild** [comment]
I just added an `environment.yml` file that can initialize a new conda environment for NeRF including all the requirements. See [Setup](https://github.com/bmild/nerf#setup).
