### ISSUE TITLE
the direction in get_rays

### ISSUE THREAD

**Issue by kwea123** [bmild/nerf#24]
May I know how do you derive this equation?
```
dirs = tf.stack([(i-W*.5)/focal, -(j-H*.5)/focal, -tf.ones_like(i)], -1)
```
I read [this article](https://www.scratchapixel.com/lessons/3d-basic-rendering/ray-tracing-generating-camera-rays/generating-camera-rays) and gained some insight on the transformation between coordinates. However, the formula seems to be different than yours, in particular the `+0.5` to center the pixels.

**Comment by bmild** [comment]
This basically applies the intrinsic matrix plus some other coordinate system related stuff: since the *y* value indexes from top to bottom, we flip it, and since the camera looks along the negative *z* axis, we negative it. In practice we didn't find the calibration precise enough for the +0.5 to matter.

**Comment by dwangxxx** [comment]
> This basically applies the intrinsic matrix plus some other coordinate system related stuff: since the _y_ value indexes from top to bottom, we flip it, and since the camera looks along the negative _z_ axis, we negative it. In practice we didn't find the calibration precise enough for the +0.5 to matter.

Why should we flip the y-axis. And according the camera calibration, the camera look along the positive z axis, why is the z-axis negative? Could you give some explanation? Thank you very much!

**Comment by BingCS** [comment]
I believe that its camera frame follows the OpenGL convention [right, up, back].

**Comment by pzdkn** [comment]
what's the focal length doing here? Isn't it one as the image plane is one offset by the camera coordinate system?
