### ISSUE TITLE
N_importance value

### ISSUE THREAD

**Issue by kwea123** [bmild/nerf#25]
In the paper you stated 

> Nc= 64coordinates in the coarse volume and Nf = 128 additional coordinates in thefine volume.

But the config files in the repo the `N_importance` is set to `64` for all scenes. If I understand correctly, `N_importance` is `Nf`, so why is it different from the paper? Also the effect of different `Nf` is not shown in the ablation study table (all experiments have `Nf=128`), does that mean `Nf` is not so important?

**Comment by bmild** [comment]
Those config files also train at lower resolution than the results in the paper and video, just for speedier convergence when trying things out. Hence the lower sample count. It is certainly important!

I've just added the exact configs to replicate the paper in the new [`paper_configs`](https://github.com/bmild/nerf/tree/master/paper_configs) directory.
