### ISSUE TITLE
number of output channels

### ISSUE THREAD

**Issue by kwea123** [bmild/nerf#27]
Normally the output has only 4 channels: rgb and sigma, but here it is set to 5 when `N_importance>0`, which is always the case in default experiments.

https://github.com/bmild/nerf/blob/c39def3944c982aa7aabeacdd2e856c07da39b9e/run_nerf.py#L388

So what does this 5th output do? I checked the code of `raw2outputs` and it seems the 5th element is never accessed, so it means the network has a redundant output?

**Comment by bmild** [comment]
You're right, this is leftover functionality from an experiment that didn't go anywhere (trying to use an additional 5th channel to predict weighting in the coarse model that was distinct from the sigma opacity channel).
