### ISSUE TITLE
tiny_nerf_data.npz missing

### ISSUE THREAD

**Issue by dmaniry** [bmild/nerf#3]
I would love to play around with the tiny nerf notebook but I can't find the file tiny_nerf_data.npz or a script that generates it.

**Comment by bmild** [comment]
It's at https://people.eecs.berkeley.edu/~bmild/nerf/tiny_nerf_data.npz, and I just updated the `download_example_data.sh` script to wget it.

**Comment by aradhyamathur** [comment]
Resource not found using the above link .

**Comment by cemlyn007** [comment]
That link doesn't work for me :(

**Comment by SumiyaBarsha** [comment]
file_name = 'tiny_nerf_data.npz'

if not os.path.exists(file_name):
  !wget --no-check-certificate https://cseweb.ucsd.edu//~viscomp/projects/LF/papers/ECCV20/nerf/tiny_nerf_data.npz

data_load = np.load('tiny_nerf_data.npz')


This worked for me
