### ISSUE TITLE
3d model from real images

### ISSUE THREAD

**Issue by TheShasa** [bmild/nerf#30]
Hello, thanks for this great work!

Can you give me a hint how can we create the 3d model same as in lego extract_mesh.ipynb example using real life images?

**Comment by Sch1nken** [comment]
If I understand the readme correct, then you could try this: 
> #Extracting geometry from a NeRF
> Check out extract_mesh.ipynb for an example of running marching cubes to extract a triangle mesh > from a trained NeRF network. You'll need the install the PyMCubes package for marching cubes > plus the trimesh and pyrender packages if you want to render the mesh inside the notebook:

> # pip install trimesh pyrender PyMCubes

**Comment by TheShasa** [comment]
So first we need to train it on our 'real image' example?

**Comment by TheShasa** [comment]
Thanks for your reply
So first we need to train it on our 'real images' example?

**Comment by bmild** [comment]
Yes, you would have to train a network on your real images. Extracting a mesh in this case is a bit more complicated since it's harder to separate the object from the background than with the synthetic data that is isolated in space.

**Comment by TheShasa** [comment]
Great, thank you for clarification!
