### ISSUE TITLE
How much video memory is needed to run the test example? 

### ISSUE THREAD

**Issue by 123Ray321** [bmild/nerf#31]
My laptop's video card is 1660Ti, and I always run out of resources.
Runtime exception：
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[4194304,90] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:ConcatV2]name: concat

**Comment by jaggzh** [comment]
@123Ray321 Did you find a solution? I face the same issue.
