### ISSUE TITLE
How to translate depth in NDC to real depth?

### ISSUE THREAD

**Issue by kwea123** [bmild/nerf#35]
When in NDC space, the predicted depth has range 0~1. How to translate that into real depth?
We know that predicted depth=0 means that it's at the near plane, which is at real distance 1.0, how about predicted depth=1? In the formula it corresponds to infinity, but in reality, do we translate that into the real farthest depth provided by COLMAP? And how about the values that are between 0 and 1?

I ask this question because I want to reconstruct the LLFF data in 3D. Using the predicted depth in 0~1 gives something visually plausible but I think it is mathematically wrong, we need to convert it to real depth.
![Screenshot from 2020-04-22 22-21-54](https://user-images.githubusercontent.com/11364490/79986901-b360d180-84e7-11ea-9f4f-e515819f79d8.png)

**Comment by bmild** [comment]
You can invert the NDC equation to get back world space values (see eqn (20) in the [NDC writeup](https://github.com/bmild/nerf/files/4451808/ndc_derivation.pdf)). If your final NDC coordinates are `(x', y', z')`, calculate:
```
z = 2 / (z' - 1)
x = -x' * z * W / 2 / f
y = -y' * z * H / 2 / f
```
to invert the transformation and get back to regular space. Note that here z should range from -1 to -infty since in NDC it should range from -1 to +1. Another note is that if you are actually using the ray `t` distance, the NDC z coordinate is `z = 2 * t - 1`, so the conversion to real depth is just `z = 1 / t`.

**Comment by kwea123** [comment]
A correction, in NDC the depth is from 0 ~ 1, which correspond to real distance of 1 to infinity, so the correct formula to convert from NDC depth `t` to real depth `z` is `z=1/(1-t)` instead of `1/(t-1)`

**Comment by kwea123** [comment]
An update on this:
![Screenshot from 2020-05-02 23-32-11](https://user-images.githubusercontent.com/11364490/80867145-85407600-8ccd-11ea-9c20-388d9476605b.png)
I successfully merged multiple depths into one point cloud, and the result looks decent, although there's inevitably some noise, especially with these complex structures in real world. I will test my method on other llff scenes, and if it works well, I will publish my code.

**Comment by roganelli** [comment]
> I successfully merged multiple depths into one point cloud, and the result looks decent, although there's inevitably some noise, especially with these complex structures in real world. I will test my method on other llff scenes, and if it works well, I will publish my code.

Super excited at this possibility. Looking forward to see any other results on other llff scenes. Would love to test this out on some that I have optimized.

**Comment by kwea123** [comment]
Actually the depth is only consistent for this scene.. For other scenes the depth of the same object varies a lot, to a degree that it's nearly impossible to fuse the points: basically if you backproject the points, you'll have many same objects lying around... so I think the point cloud fusion won't work, and I abandoned already.

**Comment by roganelli** [comment]
> Actually the depth is only consistent for this scene.. For other scenes the depth of the same object varies a lot, to a degree that it's nearly impossible to fuse the points: basically if you backproject the points, you'll have many same objects lying around... so I think the point cloud fusion won't work, and I abandoned already.

Could sparse points from Colmap or some other SfM approach be used to help calibrate the depth from better from the disparity maps that are generated?

**Comment by kwea123** [comment]
It might be helpful. But what I think an easier way to experiment first is to change how the depth is computed in this algo. Currently it's the opacity weighted traveled distance for the rays, but I've read some other papers use the isosurface of some predefined alpha threshold, e.g. we consider the depth as the distance when the accumulated opacity reaches 0.5. In my intuition this is more reasonable, although one might question how the threshold should be set. Anyway, it requires experiments, I might or might not do in the future.

**Comment by roganelli** [comment]
Would that calibrate the depth across all images or just a single image? If you are to run fusion of the depth maps you need to have consistent depth in world coordinates  to get depth for the same object to be similar across frames. correct?

**Comment by kwea123** [comment]
Yes it will be consistent across all images.

**Comment by NagabhushanSN95** [comment]
> You can invert the NDC equation to get back world space values (see eqn (20) in the [NDC writeup](https://github.com/bmild/nerf/files/4451808/ndc_derivation.pdf)). If your final NDC coordinates are `(x', y', z')`, calculate:
> 
> ```
> z = 2 / (z' - 1)
> x = -x' * z * W / 2 / f
> y = -y' * z * H / 2 / f
> ```
> 
> to invert the transformation and get back to regular space. Note that here z should range from -1 to -infty since in NDC it should range from -1 to +1. Another note is that if you are actually using the ray `t` distance, the NDC z coordinate is `z = 2 * t - 1`, so the conversion to real depth is just: `z = 2 / (2 * t - 1 - 1) = 1 / (t - 1)`

Does this take care of the final trick where the origin is moved to the near plane? `o_n = o + t_n d`

**Comment by MaybeOjbk** [comment]
> It might be helpful. But what I think an easier way to experiment first is to change how the depth is computed in this algo. Currently it's the opacity weighted traveled distance for the rays, but I've read some other papers use the isosurface of some predefined alpha threshold, e.g. we consider the depth as the distance when the accumulated opacity reaches 0.5. In my intuition this is more reasonable, although one might question how the threshold should be set. Anyway, it requires experiments, I might or might not do in the future.

I think you are right, but I get depth in two ways, one is calculate mean of. z_vals *weights, the other is  calculate the max index of weights and gather its' z_val, however using muti view depth , I can't get a consistent point cloud, I wonder if the depth from Nerf, is calculate from object to view point not to view plane, However I also tried calculate  it from view plane, muti view depth project to world space, theses points are not consistent. Do you know why?

**Comment by szgy66** [comment]
> An update on this: ![Screenshot from 2020-05-02 23-32-11](https://user-images.githubusercontent.com/11364490/80867145-85407600-8ccd-11ea-9c20-388d9476605b.png) I successfully merged multiple depths into one point cloud, and the result looks decent, although there's inevitably some noise, especially with these complex structures in real world. I will test my method on other llff scenes, and if it works well, I will publish my code.

Hi, I am very interested in you fusing multiple depth maps from LLFF dataset into 3D point cloud, even if it is not robust to other scenes, so can you share your code? Thanks
