### ISSUE TITLE
How do you create the mixed-reality video?

### ISSUE THREAD

**Issue by kwea123** [bmild/nerf#36]
How do you add the ball inside and move it?

**Comment by bmild** [comment]
The quick and easy version would be to take the generated depth map and just use z-buffering to add in a synthetic object. 

We did something a bit more complicated: basically we added 1 new sample to each ray that was at the virtual depth of the synthetic object (if that ray intersected the object) with full opacity and the RGB color from the object at that point. That is, render out RGBA+depth of your synthetic object and then splice those samples into the rays before they're accumulated.

I doubt the results would actually look that different than just taking the min of the depth map from the NeRF rendering and synthetic object though, and that would be much simpler.

**Comment by kwea123** [comment]
I thought you passed into 3d before projecting back to 2d; rendering a virtual object seems easy, but I wonder how you generated the path? It should be difficult to draw the 3d path from just 2d image. The path of the ball looks very natural, how did you design it?

**Comment by bmild** [comment]
Ah yes, you're right. I actually used an ipywidgets GUI I made for an [earlier project](https://people.eecs.berkeley.edu/~pratul/lighthouse/) that allowed me to render a live preview of an inserted object, pick 3D control points, and then generate a smooth path between them with Bezier splines. It's a horrible mess though so I can't release it, it wouldn't be usable.

**Comment by kwea123** [comment]
Thanks for the info. I'll experiment myself!

**Comment by kwea123** [comment]
Just to let you know, I realized the same effect in Unity! https://youtu.be/S5phWFTs2iM
It enables so much interesting possibilities that I can't wait to try!
