### ISSUE TITLE
Image undistortion

### ISSUE THREAD

**Issue by kwea123** [bmild/nerf#38]
Is image undistortion required? With the current COLMAP setup it seems it's not performed.
Won't the mathematical derivations be broken due to distortion?

**Comment by bmild** [comment]
In practice we didn't find the distortion on the cellphone camera images to be too severe; if you inspect reprojected plane sweep volumes of multiple images then the features line up pretty well. However, if you fix this and it improves the results please let us know :)

**Comment by kwea123** [comment]
So it does have an impact theoretically, right? It's just because cellphone camera has only small distortion so we ignore it. I think COLMAP also provides functionality to undistort the images, so the solution is actually simple: distort the images before applying this method. I just wanted to be assured that distortion actually has influence.

**Comment by bmild** [comment]
Yes theoretically you are correct, if the distortion was nontrivial it would make the generated rays completely incorrect with the assumed pinhole model.

(It's also possible the cellphone cameras do some of this correction in software themselves, given how much computation is applied to iPhone/Android images automatically after capture these days.)
