### ISSUE TITLE
tiny_nerf notebook bugs

### ISSUE THREAD

**Issue by kylemcdonald** [bmild/nerf#4]
When running the `tiny_nerf.ipynb` notebook, the final interactive cell was causing the notebook to run indefinitely. I had to change this line: `rays_o, rays_d = get_rays(H, W, focal, c2w.numpy()[:3,:4])` to add the `.numpy()`, and now it works.

I also had to remove the `print(i, psnr.numpy())` from an earlier cell, because `psnr` is not defined yet.

**Comment by tancik** [comment]
Thanks for the feedback. `tiny_nerf.ipynb` has been updated and there is now a link to a colab version in the `README.md`.
