### ISSUE TITLE
Full resolution synthesis

### ISSUE THREAD

**Issue by kwea123** [bmild/nerf#42]
What is the best way to synthesize full resolution image? For real images that have 4032x3024 image size, I tried default 1/8 scale training and it works quite well, but it already takes about 7s to synthesize an image. When I tried 1/4 scale training, first the training time increases as there are more rays, more important of all, inference time also increases quadratically (so to about 30s) with size. Of course, the image quality improves in terms of higher PSNR, but maybe not that much to human eye.

There are two alternatives I can think of: 
1. synthesize on lowres images then use some super-resolution techniques to generate highres images
2. train on full resolution using your algo

In your opinion, which one is better in practice given limited resource and time?

**Comment by bmild** [comment]
If all you want is to generate high resolution video outputs that look sharp to the eye then you could do option 1. Of course the fine details will be effectively hallucinated from a single 2d frame for each view so they won't be multiview consistent. In practice that might not really matter though (we've never actually tried this). 

We do find that moving from 1/8 scale to 1/4 scale results in learning more detail even with the same network capacity though, so you will get more detail out if you take the time to train at a higher resolution.

**Comment by kwea123** [comment]
update: first train on low res (1/8) then fine tune on high res (1/4) is a good way to reduce training time. I successfully increased val PSNR using this technique

**Comment by qsobad** [comment]
this idea sounds like curriculum training so to speak
