### ISSUE TITLE
Question about ray directions calculation in code.

### ISSUE THREAD

**Issue by zdw-qingdao** [bmild/nerf#46]
dirs = np.stack([(i-W*.5)/focal, -(j-H*.5)/focal, -np.ones_like(i)], -1)

'i','j' is the pixel coordinates, why this is the ray direction? Are there some assumptions?

Thanks a lot!

**Comment by kwea123** [comment]
#24
Do some research before you ask.

**Comment by zdw-qingdao** [comment]
@kwea123  This doesn't answer my question. Camera intrinsic matrix includes  cx,cy,fx,fy. I's still confused about why [(i-W*.5)/focal, -(j-H*.5)/focal,1] is the ray direction? 
I will be grateful if you can explain this.

**Comment by zdw-qingdao** [comment]
@kwea123 Sorry about my formulation.  [(i-W*.5)/focal, -(j-H*.5)/focal,1] is not the ray direction. But why it's the proportional physical coordinate of pixel?

**Comment by bmild** [comment]
Just to clarify, this is the same operation as the intrinsic matrix application for a simple pinhole camera, since
fx = fy = focal
and
cx = W*.5
cy = H*.5

**Comment by HtForBetterLife** [comment]
> 
hi, @zdw-qingdao , can you explain that code? I still don't understand it.

**Comment by xxmy7** [comment]
> > 
> 
> hi, @zdw-qingdao , can you explain that code? I still don't understand it.

@HtForBetterLife  
This is just a the process of converting pixel coordinates to camera coordinates.
And notice that it needs to convert the camera coordinates to opengl coordinates( x right y up z back)，so  y should add a "-" and also z = -1 rather than 1

**Comment by yiakwy-xpu-ml-framework-team** [comment]
in pinhole model or any other related SLAM, we call `[(i-W*.5)/focal, -(j-H*.5)/focal,1]` coordinates normalization.

**Comment by pzdkn** [comment]
I thought the focal length is always 1, as the image plane is shifted by one from the camera origin. What am I getting wrong here?
