### ISSUE TITLE
Why NDC space has degenerate case when capturing 360 degree views

### ISSUE THREAD

**Issue by zhengqili** [bmild/nerf#47]
Hi,

I experimented NeRF on 360-degree scenes, and if I use NDC, there are always degenerate cases like the figure shown below. I am wondering why this happens in NDC space. Does NDC only works for half-hemisphere, do you have any intuition or math explanation for this?

![playground_360_ndc](https://user-images.githubusercontent.com/7671455/81227257-2115fe80-8fba-11ea-80b4-a5001eac6b89.png)

Thanks!

**Comment by bmild** [comment]
NDC only works when the whole scene lies behind a "near" plane perpendicular to the camera axis. So yes, it will only work for a half-hemisphere scene with less than 180 degree field of view, and certainly not for 360 degree scenes.
