### ISSUE TITLE
Scalar PI is missing when creating positional encodings?

### ISSUE THREAD

**Issue by DomainFlag** [bmild/nerf#50]
I dunno if it's on purpose but the PI scalar (as in original paper) is missing when creating positional encodings for:

```
        for freq in freq_bands:
            for p_fn in self.kwargs['periodic_fns']:
                embed_fns.append(lambda x, p_fn=p_fn,
                                 freq=freq: p_fn(x * freq))
                out_dim += d
```

Line 49, on [Run Nerf Helpers](https://github.com/bmild/nerf/blob/master/run_nerf_helpers.py), is it on purpose or it's done somewhere else?

**Comment by kwea123** [comment]
#12
