### ISSUE TITLE
how to create database.db ?

### ISSUE THREAD

**Issue by stone100010** [bmild/nerf#51]
subprocess.CalledProcessError: Command '['colmap', 'feature_extractor', '--database_path', 'batman/database.db', '--image_path', 'batman/images', '--ImageReader.single_camera', '1']' returned non-zero exit status 1.

I have placed my picture in batman/images/, but I still report an error, which feels like missing some files, such as database.db or others.

**Comment by stone100010** [comment]
Resolved

**Comment by bmild** [comment]
What was the fix?
