### ISSUE TITLE
just an idea

### ISSUE THREAD

**Issue by qsobad** [bmild/nerf#55]
since you use the coarse nerf to sample the fine net,
is it possible to train course net solely for depth and then infer the fine one for color,
would it make any difference in training speed ?

or thus maybe can use different net for different purpose?
ignore if it's too naive.

**Comment by bmild** [comment]
No gradients pass from the fine network to the coarse network (we tried and found the signal was not sufficient for training the coarse network), so the coarse network must be trained with rendering loss, which means it has to output all components RGB+sigma.

**Comment by qsobad** [comment]
thanks for the insight!
