### ISSUE TITLE
original blender files

### ISSUE THREAD

**Issue by kmatzen** [bmild/nerf#59]
I followed the instructions to obtain the lego scene from blendswap and I parsed the json files to get the poses and FOV.  The poses look correct, but two pieces of info seem to be missing.  One is that the scene doesn't appear to be the correct scale.  The cameras are within the object without scaling by a factor of 25 or so.  The second is that the lego bulldozer scene has a controllable bucket and the renderings in NeRF clearly use a setting other than the default in the blendswap scene.

Do the authors still have the original blender files they used to render these scenes?  The licenses seem fairly permissive.  It would be great to use these as a starting point for new experiments, but be able to modify them.

**Comment by tancik** [comment]
I added the .blend files to the data repo - https://drive.google.com/file/d/1RjwxZCUoPlUgEWIUiuCmMmG0AhuV8A2Q/view?usp=sharing
They may require some tweaking to get running. For example, the HDR environment textures may not be correctly linked (I used the blender included ones).

**Comment by kmatzen** [comment]
Excellent, thank you @tancik!

**Comment by SeanGuo063** [comment]
Thank you for sharing the the .blend files. I have studied the scripts and notice that the 360_view_test.py is for test images, right? So I wonder how images for training and validation were generated in your paper. Just use RANDOM_VIEWS in 360_view.py and set VIEWS for 100?

**Comment by hansen7** [comment]
> I added the .blend files to the data repo - https://drive.google.com/file/d/1RjwxZCUoPlUgEWIUiuCmMmG0AhuV8A2Q/view?usp=sharing
> They may require some tweaking to get running. For example, the HDR environment textures may not be correctly linked (I used the blender included ones).

Thanks for sharing! 
May I ask how to move the bulldozer's blade lol? 

Seems that it differs from the original model from the one provided on [blendswap](https://www.blendswap.com/blend/11490).

**Comment by tancik** [comment]
<img width="637" alt="Screen Shot 2021-05-04 at 9 22 03 AM" src="https://user-images.githubusercontent.com/3310961/117036425-48c9a080-acba-11eb-8626-81bc5448ae26.png">
Move these sliders to move the bulldozer's bucket.

**Comment by bhowmickarka** [comment]
Hi, where can I find this script  "360_view_test.py"? I don't see it in the official repository.

**Comment by nestor98** [comment]
> Hi, where can I find this script "360_view_test.py"? I don't see it in the official repository.

Just spent an hour looking for it, it turns out you just have to open the .blend file and go to the `Scripting` tab inside blender itself.

**Comment by wenwhx** [comment]
Hi, I'm using Blender 2.82 and the script "360_view_test.py" to generate the testing data for Chair. I relinked the texture and HDR environment textures. But it is weird to find the final png file still has something different from that in the public testing set. I'm not sure if I have aligned all the settings. Do you have any recommended configuration that I can try to generate the same data? Thanks!

This is what I generated.
![r_0](https://user-images.githubusercontent.com/4027624/222047618-cb4501cf-928e-4d45-998d-f212d8f7a1d8.png)


This is the original one.
![r_0](https://user-images.githubusercontent.com/4027624/222047701-8ce4fa8e-cb77-4692-9e5a-f1bef3a51c12.png)

**Comment by phongnhhn92** [comment]
> I added the .blend files to the data repo - https://drive.google.com/file/d/1RjwxZCUoPlUgEWIUiuCmMmG0AhuV8A2Q/view?usp=sharing They may require some tweaking to get running. For example, the HDR environment textures may not be correctly linked (I used the blender included ones).

Hi,

Would you mind sharing the blend files again ? The link above is not working anymore.
