### ISSUE TITLE
alpha not rectified

### ISSUE THREAD

**Issue by qsobad** [bmild/nerf#62]
I wonder why the alpha_out is not rectified by ReLU which is mentioned in Fig.7
`        alpha_out = dense(1, act=None)(outputs)`

**Comment by tancik** [comment]
ReLU is applied to alpha, just in a different code location:
https://github.com/bmild/nerf/blob/8edde335d2b18188769850b03c45515352d66b31/run_nerf.py#L110

**Comment by qsobad** [comment]
ahhh,,, ic. it's the same if i add the relu after the linear layer, right?

**Comment by tancik** [comment]
Yep, it's the same.

**Comment by qsobad** [comment]
thanks man!
