### ISSUE TITLE
Normal map in blender

### ISSUE THREAD

**Issue by kwea123** [bmild/nerf#63]
How to decode the normal map in blender test set? I tried the traditional `2*rgb-1` but it doesn't look good, and the norm is not 1.

**Comment by tancik** [comment]
We never ended up using the normal maps and I believe they are faulty. They are the result of saving the "normal" render pass from blender. The method does not properly retain the complete information. I will remove them when I have the chance to avoid future confusion.

**Comment by kwea123** [comment]
Thank you!

**Comment by yd-yin** [comment]
Hi @kwea123!
Did you find something in letting the model learn the normal vectors? Do you mean to supervise the NeRF by normal maps? Thanks!
