### ISSUE TITLE
SSIM and LPIPS setup

### ISSUE THREAD

**Issue by zdw-qingdao** [bmild/nerf#66]
Could you provide the script of SSIM and LPIPS evalution or just show the setup of SSIM and LPIPS ? So we can cmpare your results better. 
Thanks a lot!

**Comment by bmild** [comment]
Using a static Tensorflow 1 graph, we call
```
image0_ph = tf.placeholder(tf.float32)
image1_ph = tf.placeholder(tf.float32)

distance_t = lpips_tf.lpips(image0_ph, image1_ph, model='net-lin', net='vgg')

psnr_tf = tf.image.psnr(image0_ph, image1_ph, max_val=1.)
ssim_tf = tf.image.ssim(image0_ph, image1_ph, max_val=1.)
```
and run through the full size rendered test images and the ground truth images (alpha-matted on a white background for the Blender scenes) scaled to be in the interval [0,1] by dividing the saved 8-bit PNGs by 255.

Note that in the original arxiv posting, we used `ssim_multiscale`. The arxiv v2 posting has been updated with actual `ssim` numbers to match the language in the paper.
