### ISSUE TITLE
ramdom direction of light sampling

### ISSUE THREAD

**Issue by qsobad** [bmild/nerf#75]
in the papar, you have perturb for the position the light sampled.
i tried to also randomise the direction of of light sampled from the camera within the box of pixel. (i + rand - W/2)/f
in contrast to fixed position (i - W/2)/f, it gets worse result.
i wondered why

**Comment by kwea123** [comment]
It sounds very similar to a common trick used in ray tracing (antialiasing), I wonder why it doesn't work..

**Comment by qsobad** [comment]
i think it might be easier for mlp to learn that way
