### ISSUE TITLE
Question about handling of deepvoxels data

### ISSUE THREAD

**Issue by Kai-46** [bmild/nerf#8]
Great work! Thanks for sharing the code.

I'm a little puzzled by how deepvoxels data is handled in **load_deepvoxels.py** [(L67-73)](https://github.com/bmild/nerf/blob/fa829f7dc64b5e6ee7a0d8ff25e2ee636291000d/load_deepvoxels.py#L67).  Since both deepvoxels and nerf use opencv convention for camera coordinate system, i.e., **x** points right, **y** points down, **z** points towards scene, why does one need to multiply the deepvoxels pose with **transf** (shown below)? I don't get why we need to flip the **y,z** axes of the camera coordinate system used by deepvoxels. Any help is appreciated!

`       transf = np.array([
            [1,0,0,0],
            [0,-1,0,0],
            [0,0,-1,0],
            [0,0,0,1.],
        ])  <br/>
        poses = poses @ transf`

**Comment by bmild** [comment]
Ah I made a significant mistake in the readme -- I meant to write that the pose convention is the same as **OpenGL**, not COLMAP. It's [right, up, backwards] actually.

**Comment by Kai-46** [comment]
That make sense. Thank you for the answer. 

If you have time, can you take a look at **load_deepvoxels.py** [L97-98](https://github.com/bmild/nerf/blob/abb6247340ce93a81512e222b366b9126b464d75/load_deepvoxels.py#L97). I believe there might be a bug there.

**Comment by bmild** [comment]
You're correct, thanks for catching that. Just pushed a fix and a config file for the `greek` deepvoxels shape.
