### ISSUE TITLE
script to generate training and validation data using blender file

### ISSUE THREAD

**Issue by ShougangShen** [bmild/nerf#89]
I an interested in your project. I have the same question about .blend files as @SeanGuo063.  _I have studied the scripts and notice that the 360_view_test.py is for test images, right? So I wonder how images for training and validation were generated in your paper. Just use RANDOM_VIEWS in 360_view.py and set VIEWS for 100?_

**Comment by tancik** [comment]
Yep, that is correct.

**Comment by ShougangShen** [comment]
OK, thank you for your reply!

**Comment by BingCS** [comment]
Where can I get the file 360_view_test.py? Could you please give me the link? Many thanks!
